### ISSUE TITLE
Salt error :  `KeyError: 'config.get'`

### ISSUE THREAD

**Issue by nicolas-t** [lightrush/framework-laptop-formula#33]
Hello,

I just upgraded to ubuntu 22 again :)
I try to run the formula but I am returned a python error : 
`KeyError: 'config.get'`

Full output :  
`» wget -O /tmp/framework-laptop-tldr.sh https://raw.githubusercontent.com/lightrush/framework-laptop-formula/main/framework-laptop-tldr.sh && bash /tmp/framework-laptop-tldr.sh`

```
--2022-05-26 19:39:36--  https://raw.githubusercontent.com/lightrush/framework-laptop-formula/main/framework-laptop-tldr.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 868 [text/plain]
Saving to: ‘/tmp/framework-laptop-tldr.sh’

/tmp/framework-laptop-tldr.sh       100%[=================================================================>]     868  --.-KB/s    in 0s      

2022-05-26 19:39:37 (92.5 MB/s) - ‘/tmp/framework-laptop-tldr.sh’ saved [868/868]

Hit:1 http://fr.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://fr.archive.ubuntu.com/ubuntu jammy-updates InRelease   
Hit:3 https://updates.signal.org/desktop/apt xenial InRelease       
Get:4 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:5 http://fr.archive.ubuntu.com/ubuntu jammy-backports InRelease [99.8 kB]
Fetched 210 kB in 1s (228 kB/s)                                     
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  libc++1
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
salt-common is already the newest version (3004.1+dfsg-2).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
--2022-05-26 19:39:43--  https://github.com/lightrush/framework-laptop-formula/archive/refs/heads/main.zip
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/lightrush/framework-laptop-formula/zip/refs/heads/main [following]
--2022-05-26 19:39:43--  https://codeload.github.com/lightrush/framework-laptop-formula/zip/refs/heads/main
Resolving codeload.github.com (codeload.github.com)... 140.82.121.9
Connecting to codeload.github.com (codeload.github.com)|140.82.121.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 363558 (355K) [application/zip]
Saving to: ‘framework-laptop-formula-main.zip’

framework-laptop-formula-main.zip   100%[=================================================================>] 355.04K  1.02MB/s    in 0.3s    

2022-05-26 19:39:44 (1.02 MB/s) - ‘framework-laptop-formula-main.zip’ saved [363558/363558]

Archive:  framework-laptop-formula-main.zip
925443a4ddbca2c1612e278cab216d982a5e7731
  inflating: framework-laptop-formula-main/.gitignore  
  inflating: framework-laptop-formula-main/LICENSE  
  inflating: framework-laptop-formula-main/README.md  
  inflating: framework-laptop-formula-main/framework-laptop-tldr.sh  
  inflating: framework-laptop-formula-main/framework-laptop/defaults.yaml  
  inflating: framework-laptop-formula-main/framework-laptop/files/10-framework-sec-trim.rules  
  inflating: framework-laptop-formula-main/framework-laptop/files/com.ubuntu.enable-hibernate.pkla  
  inflating: framework-laptop-formula-main/framework-laptop/files/fingerprint-reader/libfprint_delete_device_prints.py  
  inflating: framework-laptop-formula-main/framework-laptop/files/fingerprint-reader/prebuilt/debian.libfprint.install.patch  
  inflating: framework-laptop-formula-main/framework-laptop/files/fingerprint-reader/prebuilt/debian.rules.patch  
  inflating: framework-laptop-formula-main/framework-laptop/files/fingerprint-reader/prebuilt/fprintd-doc_1.94.0-1_all.deb  
  inflating: framework-laptop-formula-main/framework-laptop/files/fingerprint-reader/prebuilt/fprintd_1.94.0-1_amd64.deb  
  inflating: framework-laptop-formula-main/framework-laptop/files/fingerprint-reader/prebuilt/gir1.2-fprint-2.0_1.94.1-1_amd64.deb  
  inflating: framework-laptop-formula-main/framework-laptop/files/fingerprint-reader/prebuilt/libfprint-2-2_1.94.1-1_amd64.deb  
  inflating: framework-laptop-formula-main/framework-laptop/files/fingerprint-reader/prebuilt/libfprint-2-doc_1.94.1-1_all.deb  
  inflating: framework-laptop-formula-main/framework-laptop/files/fingerprint-reader/prebuilt/libpam-fprintd_1.94.0-1_amd64.deb  
  inflating: framework-laptop-formula-main/framework-laptop/files/intel-audio-workaround.conf  
  inflating: framework-laptop-formula-main/framework-laptop/files/intel-ax210-workaround.conf  
  inflating: framework-laptop-formula-main/framework-laptop/files/intel-ax210-workaround.service  
  inflating: framework-laptop-formula-main/framework-laptop/files/touchpad-suspend-workaround  
  inflating: framework-laptop-formula-main/framework-laptop/fingerprint-reader.sls  
  inflating: framework-laptop-formula-main/framework-laptop/framework-sec-trim-enable.sls  
  inflating: framework-laptop-formula-main/framework-laptop/grub-cleanup.sls  
  inflating: framework-laptop-formula-main/framework-laptop/grub-decrease-menu-timeout.sls  
  inflating: framework-laptop-formula-main/framework-laptop/hibernate.sls  
  inflating: framework-laptop-formula-main/framework-laptop/hpet-disable.sls  
  inflating: framework-laptop-formula-main/framework-laptop/init.sls  
  inflating: framework-laptop-formula-main/framework-laptop/intel-audio-workaround.sls  
  inflating: framework-laptop-formula-main/framework-laptop/intel-ax210-workaround.sls  
  inflating: framework-laptop-formula-main/framework-laptop/intel-xe-tearing-workaround.sls  
  inflating: framework-laptop-formula-main/framework-laptop/map.jinja  
  inflating: framework-laptop-formula-main/framework-laptop/mem-sleep-default.sls  
  inflating: framework-laptop-formula-main/framework-laptop/mouse-accel-profile.sls  
  inflating: framework-laptop-formula-main/framework-laptop/oscodenamemap.yaml  
  inflating: framework-laptop-formula-main/framework-laptop/osfamilymap.yaml  
  inflating: framework-laptop-formula-main/framework-laptop/osmap.yaml  
  inflating: framework-laptop-formula-main/framework-laptop/pillar.example  
  inflating: framework-laptop-formula-main/framework-laptop/post-resume-power-draw-workaround.sls  
  inflating: framework-laptop-formula-main/framework-laptop/pulseaudio-bt-hires-codecs.sls  
  inflating: framework-laptop-formula-main/framework-laptop/salt-masterless.sls  
  inflating: framework-laptop-formula-main/framework-laptop/tlp.sls  
  inflating: framework-laptop-formula-main/framework-laptop/touchpad-click-method.sls  
  inflating: framework-laptop-formula-main/framework-laptop/touchpad-suspend-workaround.sls  
  inflating: framework-laptop-formula-main/framework-laptop/vmware-graphics-acceleration.sls  
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 33, in <module>
    sys.exit(load_entry_point('salt==3004.1', 'console_scripts', 'salt-call')())
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 432, in salt_call
    client.run()
  File "/usr/lib/python3/dist-packages/salt/cli/call.py", line 55, in run
    caller.run()
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 111, in run
    ret = self.call()
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 218, in call
    ret["return"] = self.minion.executors[fname](
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 10, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/state.py", line 793, in apply_
    return sls(mods, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/state.py", line 1295, in sls
    opts["test"] = _get_test_value(test, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/state.py", line 475, in _get_test_value
    elif __salt__["config.get"]("test", omit_opts=True) is True:
  File "/usr/lib/python3/dist-packages/salt/loader/context.py", line 78, in __getitem__
    return self.value()[item]
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 334, in __getitem__
    super().__getitem__(item)  # try to get the item from the dictionary
  File "/usr/lib/python3/dist-packages/salt/utils/lazy.py", line 105, in __getitem__
    raise KeyError(key)
KeyError: 'config.get'
```

Nobody on the internet seems to be having the same issue, so I was wondering if you have any idea of what is happening ?

Thanks

**Comment by lightrush** [comment]
Yeah, seems like Salt itself is throwing this error. Try purging the `salt-common` and `salt-minion` packages, then re-run the TL;DR script.

**Comment by nicolas-t** [comment]
Woot I made it !
I tried purging `salt-common` and `salt-minion` but it wasn't enough.

Very randomly I tried following the instructions here : https://repo.saltproject.io/#ubuntu
and also installed `salt-master` and it worked.

Thanks for you help :) 

My computed will finally go to hibernation \o/

**Comment by lightrush** [comment]
You might want to uninstall salt-master if you aren't using it. It isn't required for this stuff and it just runs in the background consuming resources.

**Comment by nicolas-t** [comment]
Good to know thanks !
I think what fixed my issue was using different repo, maybe

**Comment by robincafolla** [comment]
This is still an issue on Ubuntu 22.04. Purging / re-installing / installing `salt-master` didn't help.

**Comment by lightrush** [comment]
Does it happen every time?
